// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqb3VRoBRVcrlAuN8JtcDYUGDX6EVrAaw',
    appId: '1:979997069517:web:2ba79ca5647758cdf45984',
    messagingSenderId: '979997069517',
    projectId: 'tales-of-tourists-d1f77',
    authDomain: 'tales-of-tourists-d1f77.firebaseapp.com',
    storageBucket: 'tales-of-tourists-d1f77.appspot.com',
    measurementId: 'G-89P6R3XZEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzPky4EfS4tvStxE3pNA2wRr-LV_CjGo0',
    appId: '1:979997069517:android:4d5d5933405a3bacf45984',
    messagingSenderId: '979997069517',
    projectId: 'tales-of-tourists-d1f77',
    storageBucket: 'tales-of-tourists-d1f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3OiaQiCULqEi6Jz7N7PMk1u0TTYr0BWU',
    appId: '1:979997069517:ios:63a547645f6628bdf45984',
    messagingSenderId: '979997069517',
    projectId: 'tales-of-tourists-d1f77',
    storageBucket: 'tales-of-tourists-d1f77.appspot.com',
    iosClientId: '979997069517-tjub1oqc2eodhiocrd8k8btl0asd1ofs.apps.googleusercontent.com',
    iosBundleId: 'com.example.talesOfTourists',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3OiaQiCULqEi6Jz7N7PMk1u0TTYr0BWU',
    appId: '1:979997069517:ios:63a547645f6628bdf45984',
    messagingSenderId: '979997069517',
    projectId: 'tales-of-tourists-d1f77',
    storageBucket: 'tales-of-tourists-d1f77.appspot.com',
    iosClientId: '979997069517-tjub1oqc2eodhiocrd8k8btl0asd1ofs.apps.googleusercontent.com',
    iosBundleId: 'com.example.talesOfTourists',
  );
}
